export const ALL_COLORS = [
  { name: 'Black' },
  { name: 'White' },
  { name: 'Navy' },
  { name: 'Gray' },
  { name: 'Beige' },
  { name: 'Brown' },
  { name: 'Red' },
  { name: 'Blue' },
  { name: 'Green' },
  { name: 'Yellow' },
  { name: 'Pink' },
  { name: 'Purple' },
  { name: 'Orange' },
  { name: 'Khaki' },
  { name: 'Cream' },
  { name: 'Burgundy' },
  { name: 'Olive' },
  { name: 'Denim' },
  { name: 'Multi' },
] as const

export const ALL_SIZES = [
  'XS',
  'S',
  'M',
  'L',
  'XL',
  'XXL',
  '2',
  '4',
  '6',
  '8',
  '10',
  '12',
  '14',
  '16',
  'One Size',
  'Free Size',
] as const
