import type { Metadata, Viewport } from "next";
import { StackProvider, StackTheme } from "@stackframe/stack";
import { stackClientApp } from "@/stack/client";
import { stackServerApp } from "@/stack/server";
import "@/styles/globals.css";
import { satoshi } from "@/styles/fonts";
import HolyLoader from "holy-loader";
import Providers from "./providers";
import ConditionalLayout from "@/components/layout/ConditionalLayout";
import AuthSync from "@/components/auth/AuthSync";

export const metadata: Metadata = {
  title: "Shopco",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  themeColor: "#000000",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={satoshi.className}><StackProvider app={stackClientApp}><StackTheme><StackProvider app={stackServerApp}><StackTheme>
        <HolyLoader color="#868686" />
        <Providers>
          <AuthSync />
          <ConditionalLayout>
            {children}
          </ConditionalLayout>
        </Providers>
      </StackTheme></StackProvider></StackTheme></StackProvider></body>
    </html>
  );
}
